### ISSUE TITLE
侧滑返回失效

### ISSUE THREAD

**Issue by hotdog12345a** [lsmakethebest/LSPanSwiper#2]
在BaseNavigationController中
    [self openSwiper];
    self.canInteractivePop=NO;

所有侧滑返回失效

**Comment by lsmakethebest** [comment]
就是这样的啊，你设置成no了，就是不能手势交互式pop了，只能点击返回按钮pop




在2018年07月10日 17:33，hotdog12345a 写道：

在BaseNavigationController中
[self openSwiper];
self.canInteractivePop=NO;

所有侧滑返回失效
